name: Tests code coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
        env:
          SOLIDITY_COVERAGE: true
          CONTINUOUS_INTEGRATION: true
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}